services:
  techexpress.application:
    image: ${DOCKER_REGISTRY-}techexpressapplication
    build:
      context: .
      dockerfile: TechExpress.Application/Dockerfile

  
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest

  distributedcache:
    image: redis


volumes:
  mssql_data: